CREATE TABLE `gz_second_house` (
  `id` INT(6) NOT NULL AUTO_INCREMENT,
  `property` VARCHAR(1024) DEFAULT NULL,
  `area` VARCHAR(1024) DEFAULT NULL,
  `section` VARCHAR(1024) DEFAULT NULL,
  `address` VARCHAR(1024) DEFAULT NULL,
  `layout` VARCHAR(1024) DEFAULT NULL,
  `price` VARCHAR(1024) DEFAULT NULL,
  `average_price` VARCHAR(1024) DEFAULT NULL,
  `contact` VARCHAR(1024) DEFAULT NULL,
  `identity` VARCHAR(1024) DEFAULT NULL,
  `phone` VARCHAR(1024) DEFAULT NULL,
  `website` VARCHAR(1024) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8